# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Enter in the city name', max_length=45)),
            ],
        ),
    ]
